### ISSUE TITLE
궁금한점이 있습니다. 

### ISSUE THREAD

**Issue by HajunKim** [ukairia777/KoBERTopic#1]
Bertopic 코드를 얼추 읽어보다가 여기서 사용하시는 tokenizer 는 vectorizer 에 들어가는거고, 실제 embedding 을 뽑기위해 넣는 input 전에는 Bertopic에서 구현해놓은 tokenizer를 쓰는 듯 하네요..? 혹시 맞을까요? 맞다면 이유가 있으신지 궁금합니다. 

감사합니다.

**Comment by ukairia777** [comment]
Bertopic에서 구현한 tokenizer를 사용하는 부분이 코드 중에서 어딜 말씀하시는 걸까요?

model = BERTopic(embedding_model="sentence-transformers/xlm-r-100langs-bert-base-nli-stsb-mean-tokens", \
                 vectorizer_model=vectorizer,
                 nr_topics=50,
                 top_n_words=10,
                 calculate_probabilities=True)
                 
저기서 vectorizer는 Mecab을 사용해서 만든 CountVectorizer이고 이건 BERTtopic에서 제공하는 토크나이저는 아닙니다.
CountVectorizer는 Document Term Matrix를 만드는 라이브러리로 BERTopic과는 별개입니다.

**Comment by HajunKim** [comment]
답변 주셔서 감사합니다. 제가 문맥을 잘 못 이해했었습니다. 
좋은 작업해주셔서 감사합니다.
